name: Tor Bridges Auto-Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'

permissions:
  contents: write

jobs:
  update-bridges:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install requests tqdm

    - name: Run Bridge Tester Script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python bridge_tester.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "action@github.com"
        
        if [ -f "Tor-Bridges-Tester.zip" ]; then
          git add *.txt Tor_Bridges_Configs.zip
          git commit -m "ðŸ”„ Update Tor Bridges [$(date)]" || echo "No changes to commit"
          git push
        else
          echo "No ZIP file found to upload."
        fi
